language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm test

before_deploy:
  - npm install -g chrome-webstore-upload-cli

deploy:
  - provider: script
    script: ./scripts/deploy.js
    skip_cleanup: true
    on:
      master: true
