language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm test

deploy:
  - provider: script
    script: chmod +x ./scripts/deploy.js && ./scripts/deploy.js
    skip_cleanup: true
    on:
      master: true
